export const fakeData =
[{
  "id": 1,
  "img": "https://eastceylon.com/images/2021/06/28/images.jpg",
  "name": "Black & Gray-t-shirt",
  "price": 50,
  "status": "hot",
  "catagori" : "product",
}, {
  "id": 2,
  "img": "https://eastceylon.com/images/2021/06/28/Flannel-Shirt.jpg",
  "name": "Flannel-Shirt",
  "price": 102,
  "status": "new",
  "catagori" : "product"
}, {
  "id": 3,
  "img": "https://eastceylon.com/images/2021/06/28/former-t-shirt.jpg",
  "name": "Former-T-Shirt",
  "price": 80,
  "status": "hot",
  "catagori" : "product",
}, {
  "id": 4,
  "img": "https://eastceylon.com/images/2021/06/28/christmas-naughty-list-tree-womens-premium-hoodie.jpg",
  "name": "Womens-Shirt",
  "price": 40,
  "status": "hot",
  "catagori" : "product",
},{
    "id": 5,
    "img": "https://eastceylon.com/images/2021/06/28/means-t-shirt.jpg",
    "name": "Means-t-shirt",
    "price": 144,
    "status": "new",
    "catagori" : "product",
  },  {
    "id": 6,
    "img": "https://eastceylon.com/images/2021/06/28/nice-list-customizable-text-christmas-mens-hoodie.jpg",
    "name": "Green-women-shirt",
    "price": 118,
    "status": "new",
    "catagori" : "product",
  }, 
  {
    "id": 7,
    "img":"https://eastceylon.com/images/2021/06/28/Office-Shirt.jpg" ,
    "name": "Office-T-Shirt",
    "price": 70,
    "status": "hot",
    "catagori" : "product",
  }, {
    "id": 8,
    "img": "https://eastceylon.com/images/2021/06/28/Oxford-Button-Down-Shirt.jpg",
    "name": "Oxford-button-shirt",
    "price": 103,
    "status": "new",
    "catagori" : "product",
  },

  {
    "id": 9,
    "img": "https://eastceylon.com/images/2021/06/08/acer.jpg",
    "name": "Acer",
    "price": 500,
    "status": "hot",
    "catagori" : "laptop",
  }, {
    "id":10 ,
    "img": "https://eastceylon.com/images/2021/06/08/images-2.jpg",
    "name": "Doel-Laptop",
    "price": 602,
    "status": "new",
    "catagori" : "laptop",
  }, {
    "id":11 ,
    "img": "https://eastceylon.com/images/2021/06/08/Macbook.jpg",
    "name": "Mackbook",
    "price": 909,
    "status": "hot",
    "catagori" : "laptop",
  }, {
    "id": 12,
    "img": "https://eastceylon.com/images/2021/06/08/Dell.jpg",
    "name": "Dell",
    "price": 760,
    "status": "hot",
    "catagori" : "laptop",
  },{
      "id":13 ,
      "img": "https://eastceylon.com/images/2021/06/08/lenevo.jpg",
      "name": "Lenovo",
      "price": 644,
      "status": "new",
      "catagori" : "laptop",
    },  {
      "id":14 ,
      "img": "https://eastceylon.com/images/2021/06/08/hp.jpg",
      "name": "Hp",
      "price": 818,
      "status": "new",
      "catagori" : "laptop",
    }, 
    {
      "id":15 ,
      "img":"https://eastceylon.com/images/2021/06/08/Asus.jpg" ,
      "name": "Asus",
      "price": 768,
      "status": "hot",
      "catagori" : "laptop",
    }, {
      "id":16 ,
      "img": "https://eastceylon.com/images/2021/06/08/Lemote.jpg",
      "name": "Lemote",
      "price": 484,
      "status": "new",
      "catagori" : "laptop",
    },

    {
      "id":17,
      "img": "https://eastceylon.com/images/2021/06/08/iPhone-SE-2.jpg",
      "name": "Ipone-SE2",
      "price": 500,
      "status": "hot",
      "catagori" : "mobile",
    }, {
      "id":18 ,
      "img": "https://eastceylon.com/images/2021/06/08/Apple-iPhone-11-1-500x500.jpg",
      "name": "Ipone-11",
      "price": 412,
      "status": "new",
      "catagori" : "mobile",
    }, {
      "id":19,
      "img": "https://eastceylon.com/images/2021/06/08/nokia_3_4-front_back-Fjord.png",
      "name": "Nokia",
      "price": 309,
      "status": "hot",
  "catagori" : "mobile",
    }, {
      "id": 20,
      "img": "https://eastceylon.com/images/2021/06/08/sumsung21.jpg",
      "name": "Sumsung S21",
      "price": 360,
      "status": "hot",
     "catagori" : "mobile",
    },{
        "id":21 ,
        "img": "https://eastceylon.com/images/2021/06/08/lenevof30c7b866ffcaf0d.jpg",
        "name": "Lenevo",
        "price": 244,
        "status": "new",
        "catagori" : "mobile",
      },  {
        "id":22,
        "img": "https://eastceylon.com/images/2021/06/08/huawei-p20-lite-3.jpg",
        "name": "Huawei p20",
        "price": 498,
        "status": "new",
        "catagori" : "mobile",
      }, 
      {
        "id":23 ,
        "img":"https://eastceylon.com/images/2021/06/08/vivo.jpg" ,
        "name": "Vivo",
        "price": 568,
        "status": "hot",
         "catagori" : "mobile",
      }, {
        "id":24 ,
        "img": "https://eastceylon.com/images/2021/06/08/swami.png",
        "name": "Swami",
        "price": 484,
        "status": "new",
       "catagori" : "mobile",
      },
  

]

  